# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

# TWILIO_ACCOUNT_SID: "AC963c9c6d258b05be89d0fcdf1b4ad35a",  
# TWILIO_AUTH_TOKEN: '1e9292e34414e6cad9b56f9320268a02'  

 